<?php
    session_id("session1");
	session_start();
    echo session_id()."\n";
    $_SESSION["name"] = "1";


	// variable declaration
	$username = "";
	$email    = "";
	$errors = array(); 
	$_SESSION['success'] = "";
	$comment = '5610 5602 560225 4446';


	// connect to database
	$db = mysqli_connect('127.0.0.1', 'root', 'Denis', 'Crypto');

	// REGISTER USER
	if (isset($_POST['reg_user'])) {
		// receive all input values from the form
		$username = mysqli_real_escape_string($db, $_POST['username']);
		$email = mysqli_real_escape_string($db, $_POST['email']);
		$password_1 = mysqli_real_escape_string($db, $_POST['password_1']);
		$password_2 = mysqli_real_escape_string($db, $_POST['password_2']);

		// form validation: ensure that the form is correctly filled
		if (empty($username)) { array_push($errors, "Username is required"); }
		if (empty($email)) { array_push($errors, "Email is required"); }
		if (empty($password_1)) { array_push($errors, "Password is required"); }

		if ($password_1 != $password_2) {
			array_push($errors, "The two passwords do not match");
		}

		// register user if there are no errors in the form
		if (count($errors) == 0) {
		    #Hasing the password using MD5 algorithm (hashing function)
			$password = md5($password_1);
			$query = "INSERT INTO Crypto.Alien (username, email, password,comment) 
					  VALUES('$username', '$email', '$password', '$comment')";
			mysqli_query($db, $query);

			$_SESSION['username'] = $username;
			$_SESSION['success'] = "You are now logged in";
			header('location: indexT.php');
		}

	}

	// ... 

	// LOGIN USER
	if (isset($_POST['login_user'])) {
		$username = mysqli_real_escape_string($db, $_POST['username']);
		$password = mysqli_real_escape_string($db, $_POST['password']);

		if (empty($username)) {
			array_push($errors, "Username is required");
		}
		if (empty($password)) {
			array_push($errors, "Password is required");
		}

		if (count($errors) == 0) {
			$password = md5($password);
			$query = "SELECT * FROM Crypto.Alien WHERE username='$username' AND password='$password'";
			$results = mysqli_query($db, $query);

			if (mysqli_num_rows($results) == 1) {
				$_SESSION['username'] = $username;
				$_SESSION['success'] = "You are now logged in";
				header('location: indexT.php');
			}else {
				array_push($errors, "Wrong username/password combination");
			}
		}
	}

$query = "SELECT comment FROM Crypto.Alien";
$results = mysqli_query($db, $query);

$row =mysqli_fetch_row($results);
echo "This is your Bank card No.: ".$row[0]."\n";


$query = "SELECT username FROM Crypto.Alien";
$results = mysqli_query($db, $query);

$row =mysqli_fetch_row($results);
echo "Card holder name: ________________".$row[0]."  K****"."\n"."\n";


#-----------------------------------#
# ...........Encryption.............#
#-----------------------------------#


function random_binary($bytes) {
    return base_convert(bin2hex(random_bytes($bytes)), 16, 2);
}


function encrypt_decrypt($action, $string) {


    $output = false;
    $encrypt_method = "AES-256-CBC";
    #Use generator in case you need#
    #$secret_key = random_binary(8);

    #Random generated bytes in Binary from Random.ORG#
    $secret_key = '10110010 11010011 00110010 00111110 01011100 01001110 01000011 11011000';
    $secret_iv = 'This is my secret iv';
    // hash
    $key = hash('sha256', $secret_key);


    // iv - encrypt method AES-256-CBC expects 16 bytes - else you will get a warning
    $iv = substr(hash('sha256', $secret_iv), 0, 16);

    if ( $action == 'encrypt' ) {
        $output = openssl_encrypt($string, $encrypt_method, $key, 0, $iv);
        $output = base64_encode($output);

    } else if( $action == 'decrypt' ) {
        $output = openssl_decrypt(base64_decode($string), $encrypt_method, $key, 0, $iv);
    }
    return $output;


}


$query = "SELECT comment FROM Crypto.Alien";
$results = mysqli_query($db, $query);

$row =mysqli_fetch_row($results);
$plain_txt = $row[0];



echo "Plain Text (Bank card No.) = " .$plain_txt. "\n";
$encrypted_txt = encrypt_decrypt('encrypt', $plain_txt);

echo "Encrypted Text = " .$encrypted_txt. "\n";
$decrypted_txt = encrypt_decrypt('decrypt', $encrypted_txt);


echo "Decrypted Text =" .$decrypted_txt. "\n"."\n";
if ( $plain_txt === $decrypted_txt ) echo "SUCCESS";
else echo "FAILED";
echo "\n";



#UPDATing comment field with encrypted comment
$query = "UPDATE Crypto.Alien SET comment = '$encrypted_txt'";
mysqli_query($db, $query);

?>